### ISSUE TITLE
KMS Setup

### ISSUE THREAD

**Issue by chapati23** [strong-config/node#25]
We need to allow users to pass in configuration for the KMS system they'd like to use.
We want to support Google Cloud, AWS, and Azure.

This could be handled as a config param upon initialisation:

```ts
new StrongConfig({ kmsProvider: 'aws', otherKmsParam: 'blub' }).load()
```

Ultimately, the provider-specific parameters need to be made available to the `sops` binary

**Comment by mohoff** [comment]
Having researched and thought about this more, I think this is the wrong approach.

There's no primary use-case in doing

```
const s = new StrongConfig({ kmsProvider: 'aws', otherKmsParam: 'blub' })
s.load()
```

This is because at the time of `.load()` (=decryption) , we have all the kms/key setup already contained in the `sops` metadata field. Thus, passing these options to the class constructor doesn't bring anything.

What we actually want:
- Encrypt configs with a CLI command. Here we pass the key/kms details as params.
- Decrypt configs automatically on `load()` (and with a CLI command in the future but this is out of scope of this issue.)

Now the line between `@strong-config/node` and `@strong-config/cli` gets very narrow. To make use of strong-config, which includes an encryption and a decryption, we would need both of thes packages. Moving forward, I think we have two options:

1. Keep two distinct packages. This means that `/node` is pretty much ready for a first releae at its current state. But it also means we require `/cli` for the release. This brings users the possibility to put `/node` as `dependency`, while `/cli` is in `devDependenices`.
2. Merge `/cli` into `/node`. We would make `/node` both an in-code imported module as well as a CLI tool. The main reason to do this is to have one package to make actual use of strong-config without needing a second package (which adds confusion too).

**Comment by barathvk** [comment]
Unless I'm missing something, the KMS provider is part of the `sops` encrypted file. It is already inferred by `sops` when it tries to decrypt the file

```
myapp1: ENC[AES256_GCM,data:Tr7o=,iv:1=,aad:No=,tag:k=]
app2:
    db:
        user: ENC[AES256_GCM,data:CwE4O1s=,iv:2k=,aad:o=,tag:w==]
        password: ENC[AES256_GCM,data:p673w==,iv:YY=,aad:UQ=,tag:A=]
    # private key for secret operations in app2
    key: |-
        ENC[AES256_GCM,data:Ea3kL5O5U8=,iv:DM=,aad:FKA=,tag:EA==]
an_array:
- ENC[AES256_GCM,data:v8jQ=,iv:HBE=,aad:21c=,tag:gA==]
- ENC[AES256_GCM,data:X10=,iv:o8=,aad:CQ=,tag:Hw==]
- ENC[AES256_GCM,data:KN=,iv:160=,aad:fI4=,tag:tNw==]
sops:
    kms:
    -   created_at: 1441570389.775376
        enc: CiC....Pm1Hm
        arn: arn:aws:kms:us-east-1:656532927350:key/920aff2e-c5f1-4040-943a-047fa387b27e
    -   created_at: 1441570391.925734
        enc: Ci...awNx
        arn: arn:aws:kms:ap-southeast-1:656532927350:key/9006a8aa-0fa6-4c14-930e-a2dfb916de1d
    pgp:
    -   fp: 85D77543B3D624B63CEA9E6DBC17301B491B3F21
        created_at: 1441570391.930042
        enc: |
            -----BEGIN PGP MESSAGE-----
            hQIMA0t4uZHfl9qgAQ//UvGAwGePyHuf2/zayWcloGaDs0MzI+zw6CmXvMRNPUsA
                            ...=oJgS
            -----END PGP MESSAGE-----
```

see the `kms` key in the above example.
