### ISSUE TITLE
strong-config check not recognising secrets in yml object structure

### ISSUE THREAD

**Issue by wolframhaussig** [strong-config/node#43]
Hi,

I am testing strong-config in a test project of mine but I have problems with `strong-config check`:
Strong-config recognises the following code as having a not encrypted secret:
```yml
api.url: https://test.com
api.apiSecret: top-secret
```
This config is not recognised:
```yml
api:
  url: https://test.com
  apiSecret: top-secret
```

Am I missing something or is this a bug?
