### ISSUE TITLE
Strong-config ignores properties which name is just `secret`

### ISSUE THREAD

**Issue by leosuncin** [strong-config/node#72]
With the following configuration file:

**config/development.yml**
```yaml
server:
  host: 127.0.0.1
  port: 3000

jwt:
  secret: VKQEl9vxXDFxtfrmSaYGAcBDvh9Kr1jm
```

I expect to be encrypted to:

```yaml
server:
  host: 127.0.0.1
  port: 3000

jwt:
  secret: ENC[AES256_GCM,data:bP9msrqiYiFuT6BLV34BkdH2u/FpeZ32W3JcmSYuZQUF7jiNw48AFWs263H26WfIA4sX6xJAuZ6WoCp745PPLbVjWmizvTUBGn3IUao=,iv:x16OCfTo6F+9Vz/39KRktrmcp2TdkCEesCa+x24gSBY=,tag:vJ0ixpPROTtKBsddwj6SxQ==,type:str]

sops: # SOPS encryption...
```

But `jwt.secret` it's ignored and leave it as it.

# System information

@strong-config/node 1.3.1
node.js version: 22.7.0
OS: Ubuntu 20.04 WSL
